
name: snyc-data

on:
  workflow_dispatch

jobs:
  push_to_registry:
    name: Runs Data Sync Task
    runs-on: ubuntu-latest
    steps:
      - name: docker run
        run: 'docker run --rm --env BGUSER="${{ secrets.BGUSER }}" --env BGPW="${{ secrets.BGPW }}" csae8092/arche2sparql:latest' 
