
name: snyc-data

on:
  workflow_dispatch

jobs:
  push_to_registry:
    name: Runs Data Sync Task
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker run
        run: 'docker run csae8092/arche2sparql:latest --rm --env BGUSER="${{ secrets.BGUSER }}" --env BGPW="${{ secrets.BGPW }}"' 
